# Generated by Django 3.2.7 on 2021-10-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(default='', max_length=20)),
                ('inlineRadioOptions', models.CharField(default='', max_length=20)),
                ('online', models.CharField(default='on', max_length=20)),
                ('offline', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('upi_id', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
