# Generated by Django 3.2.7 on 2021-10-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scam',
            name='offline',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scam',
            name='online',
            field=models.CharField(default='on', max_length=20, null=True),
        ),
    ]
