# Generated by Django 3.2.7 on 2021-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211004_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scam',
            name='id',
        ),
        migrations.AlterField(
            model_name='scam',
            name='phone',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
